# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a6b65451747dca5b94d5379ef6367b568e03d80af34988ac52dbe581e510a54fce66d0b430dc15570ddaa6a027374c200eecfec93007e2074b0997fcf4ef56

test:
  secret_key_base: 73f6ca736440d3f1f7071e954ff934e7391cd8912ec91e953cc34fe14fc0ff5490382a18953a2d898a35db157c8fba4e88722b4f89dc72e16fdff5974bf17539

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
